#!/bin/bash

export MASTER_NODE=hadoop-master
export SLAVE_NODE=hadoop-slave

export HADOOP_CLUSTER_PATH=/usr/local/hadoop_cluster
export ZOOKEEPER_HOME=${HADOOP_CLUSTER_PATH}/zookeeper
export HBASE_HOME=${HADOOP_CLUSTER_PATH}/hbase
export KYLIN_HOME=${HADOOP_CLUSTER_PATH}/kylin
export SPARK_HOME=$KYLIN_HOME/spark
export SPARK_CONF=$SPARK_HOME/conf
export TEZ_HOME=${HADOOP_CLUSTER_PATH}/tez
export TEZ_CONF_DIR=$TEZ_HOME/conf
export TEZ_JARS=$TEZ_HOME
export HIVE_HOME=${HADOOP_CLUSTER_PATH}/hive
export HIVE_CONF_DIR=$HIVE_HOME/conf
export HIVE_CONF=$HIVE_CONF_DIR
export HCAT_HOME=$HIVE_HOME/hcatalog
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
export HADOOP_HOME=${HADOOP_CLUSTER_PATH}/hadoop
export HADOOP_CONF=$HADOOP_HOME/etc/hadoop
export HADOOP_ROOT=$HADOOP_HOME
export HADOOP_BIN_PATH=$HADOOP_HOME/bin
export HADOOP_LIBEXEC_DIR=$HADOOP_HOME/libexec
export HADOOP_MAPRED_HOME=$HADOOP_HOME
export HADOOP_COMMON_HOME=$HADOOP_HOME
export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
export HADOOP_HDFS_HOME=$HADOOP_HOME
export YARN_HOME=$HADOOP_HOME
export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
export PATH=$PATH:$ZOOKEEPER_HOME/bin:$HADOOP_HOME/sbin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$KYLIN_HOME/bin:$HBASE_HOME/bin:$HCAT_HOME/bin:$SPARK_HOME/bin
export HADOOP_INSTALL=$HADOOP_HOME
export HBASE_CLASSPATH_PREFIX=$HIVE_HOME/lib
export HBASE_CLASSPATH=$HADOOP_CONF:$HADOOP_HOME/*:$HADOOP_HOME/lib/*:$ZOOKEEPER_HOME/*:$ZOOKEEPER_HOME/lib/*:$HIVE_HOME/*:$HIVE_HOME/lib/*
export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:$HBASE_HOME/lib/
# For enabling hive to use the Tez engine
if [ -z "$HIVE_AUX_JARS_PATH" ]; then
    export HIVE_AUX_JARS_PATH="$TEZ_JARS"
else
    export HIVE_AUX_JARS_PATH="$HIVE_AUX_JARS_PATH:$TEZ_JARS"
fi
export HADOOP_CLASSPATH=${TEZ_CONF_DIR}:${TEZ_JARS}/*:${TEZ_JARS}/lib/*

